ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    cert-manager.io/cluster-issuer: "letsencrypt-issuer-prod"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "SRSESSIONID"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "3600"
  hosts:
    - host: author-swissre-dev.maxxx.dev
      paths:
        - path: /
          instance: author
    - host: public-swissre-dev.maxxx.dev
      paths:
        - path: /
          instance: public
  tls:
    - hosts:
        - author-swissre-dev.maxxx.dev
        - public-swissre-dev.maxxx.dev
      secretName: swissre-dev-swissre-webpre-tls
image:
  pullSecrets:
    - name: gitlab
  pullPolicy: Always
magnoliaAuthor:
  rescueModeDX: False
  replicas: 1
  restartPolicy: Always
  redeploy: true
  contextPath: /
  webarchive:
    repository: registry.magnolia-platform.com/minh.nguyen/swissre-webpre/magnolia-webapp
    tag: "d079b449"
  bootstrap:
    username: "superuser"
    password: "superuser"
    instructions: ""
    extraEnv: []
  env:
    - name: instance
      value: "author"
    - name: deployment
      value: swissre-dev
    - name: magnolia.superuser.enabled
      value: "true"
    - name: magnolia.bootstrap.license.owner
      value: "training@magnolia-cms.com"
    - name: magnolia.bootstrap.license.key
      value: "LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tClZlcnNpb246IEJDUEcgdjEuNTgKCm93SjRuRzJTVDJnVFFSVEdreGlsMlZBcGV1cXBDUjdkU1RkTlNiR3dwRkRFSXFRb1JEeFVsTW51WkIyeU03UE8Kek1aRVVkVFdJbmd3SGhRcXZZZ0lLbFZSL0llQ1VDelVQd2Z4b2hWRUtuZ1NvVVhvUVUvT1ptblNReSs3anpmdgorMzdmdnAxbTk1WllMRHIrN09uOTlIVEVpMzZZdjFkT0VvZTZMcllRRlFqOWVmTjNWK200bnlwQ25zb09wckxHCmNDNDduQnRLamU0dHBRYU1nVUd0aHJqQWpBcHpJcC9KWmd4OUtHTmtqQW1ObmFTSW01SkRUREYxUmdoMEtITXgKQkJZUkdZc1JEZFU5ektGVVNqT3dBVVllNUF5Tk1OdDNrVEFSbFloN0hBdWtFOGlyU0NvUEFIM0pTRXNDd2liVApYVnhERnZNYXVub1N4QzJrUzFTWHdIS2hFTGlDcmRhMExxRHlyREIxRE5SWU9PY3c1cmdJUUFyZGhzU1cwREVWCmt2dEVrVVBScHR5T2t6TDFPbTdxODVTUWhYU3V3amdVaDJnc0VjREU0NndXd0NsRmxtUmNoellyYjRSM3FuVkwKeVpncmxLOUNzMDJ6NkxBTUpCSkJWN2NoQVNMWGVwVWIxRVpjUTNhTEw4d05VMjNJTVE5YVZYM0RqanNsVUVrcgpTQVIvRkxydE1LSEE4b1VNdG14RENjTU84eVFtK0ZRclQ5aHBKKzBFRFE5VXRsYWhCUnNSWnRZd0RPM1NiRHdXCmpVVzJiWTBGMXl5aUpYclc3K0hOZkR4eW9WQW9vdWJYbjJkUFR5NGRYSDV3OTlhK2wrTmozNDhtRHl4MjdhbkgKbjh4ZVAxTXlraXU3bmF2OTNRdm5kenE5cnhJekN5dUw1MWh6YlRUOW92a3huWmo2ZDAxY25qK3gvTHM0dGFOUQpuZHZ2OTE1OHVEcTlXdnA4bzcveDZKRCs1ZDN6dnJkOXY1Qjh2MzFrN3M3WTY4ZUh1NWF1OUh6N2RQdkhwRFBECmpxejlCeWtqT0VZPQo9aVk1cgotLS0tLUVORCBQR1AgTUVTU0FHRS0tLS0tCg=="
    - name: magnolia.yaml.envsubst
      value: "true"
  setenv:
    memory:
      maxPercentage: 80
  resources:
    requests:
      memory: 6Gi
    limits:
      memory: 6Gi
  livenessProbe:
    enabled: true
    path: "/.rest/status"
  db:
    tag: 15.4-alpine
    persistence:
      size: "20Gi"
    contentsync:
      enabled: true
    restore:
      enabled: False
    backup:
      enabled: True
      env:
        - name: MGNLBACKUP_PG_DATA
          value: "/db/data"
        - name: MGNLBACKUP_USE_PG_WAL
          value: "true"
        - name: MGNLBACKUP_SYNC_DIR
          value: "/archive"
        - name: MGNLBACKUP_NO_STDOUT
          value: "true"
        - name: MGNLBACKUP_LOGLEVEL
          value: "debug"
        - name: MGNLBACKUP_HERITAGE
          value: "magnolia-backup"
        - name: MGNLBACKUP_BUCKET
          value: "swissre-webpre-backup-bucket"
        - name: MGNLBACKUP_PREFIX
          value: "swissre-dev/author"
        - name: MGNLBACKUP_ADDRESS
          value: "0.0.0.0:9999"
        - name: MGNLBACKUP_CRON
          value: "0 3 * * *"
        - name: MGNLBACKUP_KEEPDAYS
          value: "30"
        - name: MGNLBACKUP_S3_ENDPOINT
          value: "s3.ap-southeast-1.amazonaws.com"
        - name: MGNLBACKUP_S3_REGION
          value: "ap-southeast-1"
        - name: MGNLBACKUP_S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: s3-backup-key
              key: accesskey
        - name: MGNLBACKUP_S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: s3-backup-key
              key: secretkey
        - name: MGNLBACKUP_TAGS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MGNLBACKUP_TAGS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MGNLBACKUP_TAGS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MGNLBACKUP_TAGS_RELEASE
          value: swissre-dev
  catalinaExtraEnv:
    magnolia.content.bootstrap.dir: '/mgnl-home/modules/bootstraps'
    magnolia.content.bootstrap.createTasks: onchange
    magnolia.yaml.envsubst: 'true'
magnoliaPublic:
  rescueModeDX: False
  redirects:
    enabled: true
  replicas: 1
  restartPolicy: Always
  contextPath: /
  webarchive:
    repository: registry.magnolia-platform.com/minh.nguyen/swissre-webpre/magnolia-webapp
    tag: "d079b449"
  bootstrap:
    username: "superuser"
    password: "superuser"
    instructions: ""
    extraEnv: []
  env:
    - name: instance
      value: "public"
    - name: deployment
      value: swissre-dev
    - name: magnolia.superuser.enabled
      value: "true"
    - name: magnolia.bootstrap.license.owner
      value: "training@magnolia-cms.com"
    - name: magnolia.bootstrap.license.key
      value: "LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tClZlcnNpb246IEJDUEcgdjEuNTgKCm93SjRuRzJTVDJnVFFSVEdreGlsMlZBcGV1cXBDUjdkU1RkTlNiR3dwRkRFSXFRb1JEeFVsTW51WkIyeU03UE8Kek1aRVVkVFdJbmd3SGhRcXZZZ0lLbFZSL0llQ1VDelVQd2Z4b2hWRUtuZ1NvVVhvUVUvT1ptblNReSs3anpmdgorMzdmdnAxbTk1WllMRHIrN09uOTlIVEVpMzZZdjFkT0VvZTZMcllRRlFqOWVmTjNWK200bnlwQ25zb09wckxHCmNDNDduQnRLamU0dHBRYU1nVUd0aHJqQWpBcHpJcC9KWmd4OUtHTmtqQW1ObmFTSW01SkRUREYxUmdoMEtITXgKQkJZUkdZc1JEZFU5ektGVVNqT3dBVVllNUF5Tk1OdDNrVEFSbFloN0hBdWtFOGlyU0NvUEFIM0pTRXNDd2liVApYVnhERnZNYXVub1N4QzJrUzFTWHdIS2hFTGlDcmRhMExxRHlyREIxRE5SWU9PY3c1cmdJUUFyZGhzU1cwREVWCmt2dEVrVVBScHR5T2t6TDFPbTdxODVTUWhYU3V3amdVaDJnc0VjREU0NndXd0NsRmxtUmNoellyYjRSM3FuVkwKeVpncmxLOUNzMDJ6NkxBTUpCSkJWN2NoQVNMWGVwVWIxRVpjUTNhTEw4d05VMjNJTVE5YVZYM0RqanNsVUVrcgpTQVIvRkxydE1LSEE4b1VNdG14RENjTU84eVFtK0ZRclQ5aHBKKzBFRFE5VXRsYWhCUnNSWnRZd0RPM1NiRHdXCmpVVzJiWTBGMXl5aUpYclc3K0hOZkR4eW9WQW9vdWJYbjJkUFR5NGRYSDV3OTlhK2wrTmozNDhtRHl4MjdhbkgKbjh4ZVAxTXlraXU3bmF2OTNRdm5kenE5cnhJekN5dUw1MWh6YlRUOW92a3huWmo2ZDAxY25qK3gvTHM0dGFOUQpuZHZ2OTE1OHVEcTlXdnA4bzcveDZKRCs1ZDN6dnJkOXY1Qjh2MzFrN3M3WTY4ZUh1NWF1OUh6N2RQdkhwRFBECmpxejlCeWtqT0VZPQo9aVk1cgotLS0tLUVORCBQR1AgTUVTU0FHRS0tLS0tCg=="
    - name: magnolia.yaml.envsubst
      value: "true"
  setenv:
    memory:
      maxPercentage: 60
  resources:
    requests:
      memory: 6Gi
    limits:
      memory: 6Gi
  livenessProbe:
    enabled: true
    path: "/.rest/status"
  db:
    tag: 15.4-alpine
    persistence:
      size: "20Gi"
    contentsync:
      enabled: true
    restore:
      enabled: False
    backup:
      enabled: True
      env:
        - name: MGNLBACKUP_PG_DATA
          value: "/db/data"
        - name: MGNLBACKUP_USE_PG_WAL
          value: "true"
        - name: MGNLBACKUP_SYNC_DIR
          value: "/archive"
        - name: MGNLBACKUP_NO_STDOUT
          value: "true"
        - name: MGNLBACKUP_LOGLEVEL
          value: "debug"
        - name: MGNLBACKUP_HERITAGE
          value: "magnolia-backup"
        - name: MGNLBACKUP_BUCKET
          value: "swissre-webpre-backup-bucket"
        - name: MGNLBACKUP_PREFIX
          value: "swissre-dev/public"
        - name: MGNLBACKUP_ADDRESS
          value: "0.0.0.0:9999"
        - name: MGNLBACKUP_CRON
          value: "0 3 * * *"
        - name: MGNLBACKUP_KEEPDAYS
          value: "30"
        - name: MGNLBACKUP_S3_ENDPOINT
          value: "s3.ap-southeast-1.amazonaws.com"
        - name: MGNLBACKUP_S3_REGION
          value: "ap-southeast-1"
        - name: MGNLBACKUP_S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: s3-backup-key
              key: accesskey
        - name: MGNLBACKUP_S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: s3-backup-key
              key: secretkey
        - name: MGNLBACKUP_TAGS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MGNLBACKUP_TAGS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MGNLBACKUP_TAGS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MGNLBACKUP_TAGS_RELEASE
          value: swissre-dev
  catalinaExtraEnv:
    magnolia.content.bootstrap.dir: '/mgnl-home/modules/bootstraps'
    magnolia.content.bootstrap.createTasks: onchange
    magnolia.yaml.envsubst: 'true'
# Additional jars which should be loaded into tomcat can be specified here.
jars:
  - name: jmx-exporter
    repository: registry.gitlab.com/mironet/magnolia-jar
    tag: jmx_prometheus_javaagent-0.13.0
    env:
      - name: INIT_DEST
        value: /extraLibs/
    initScript: /init.sh
#sharedDb:
#  enabled: true
#  workspaces:
#    - marketplace-submissions
#  db:
#    #    be careful here. PROD is still tag: 12.8, we only apply 15.4-alpine when PROD db is upgraded.
#    tag: 15.4-alpine
#    # do not migrate shared DB
#    migrate: False
#    persistence:
#      size: "20Gi"
#    contentsync:
#      # look like helm chart does not create the required mtls secret for sharedDb
#      enabled: False
#    restore:
#      enabled: False
#    backup:
#      enabled: True
#      env:
#        - name: MGNLBACKUP_PG_DATA
#          value: "/db/data"
#        - name: MGNLBACKUP_USE_PG_WAL
#          value: "true"
#        - name: MGNLBACKUP_SYNC_DIR
#          value: "/archive"
#        - name: MGNLBACKUP_NO_STDOUT
#          value: "true"
#        - name: MGNLBACKUP_LOGLEVEL
#          value: "debug"
#        - name: MGNLBACKUP_HERITAGE
#          value: "magnolia-backup"
#        - name: MGNLBACKUP_BUCKET
#          value: "swissre-webpre-backup-bucket"
#        - name: MGNLBACKUP_PREFIX
#          value: "swissre-dev/shared"
#        - name: MGNLBACKUP_ADDRESS
#          value: "0.0.0.0:9999"
#        - name: MGNLBACKUP_CRON
#          value: "0 3 * * *"
#        - name: MGNLBACKUP_KEEPDAYS
#          value: "30"
#        - name: MGNLBACKUP_S3_ENDPOINT
#          value: "s3.ap-southeast-1.amazonaws.com"
#        - name: MGNLBACKUP_S3_REGION
#          value: "ap-southeast-1"
#        - name: MGNLBACKUP_S3_ACCESSKEY
#          valueFrom:
#            secretKeyRef:
#              name: s3-backup-key
#              key: accesskey
#        - name: MGNLBACKUP_S3_SECRETKEY
#          valueFrom:
#            secretKeyRef:
#              name: s3-backup-key
#              key: secretkey
#        - name: MGNLBACKUP_TAGS_NODE_NAME
#          valueFrom:
#            fieldRef:
#              fieldPath: spec.nodeName
#        - name: MGNLBACKUP_TAGS_NAMESPACE
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.namespace
#        - name: MGNLBACKUP_TAGS_POD_NAME
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.name
#        - name: MGNLBACKUP_TAGS_RELEASE
#          value: swissre-dev
